name: thermonets
channels:
  - conda-forge
  - pytorch
dependencies:
  - c-compiler
  - cxx-compiler
  - ninja
  - cmake >=3.18
  - heyoka.py
  - pygmo
  - pip
  - matplotlib
  - jupyter
  - pykep
  - astropy
  - pytorch
  - pip:
    - nrlmsise00
    - spaceweather
    - hwm93
